### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages/proto-repl/lib/lein-runner.coffee'

### ISSUE THREAD

**Issue by xpndrobserved** [jasongilman/proto-repl#107]
Hey there.
When trying to start a REPL in atom, I receive this error. Are there any dependencies that I'm missing? On OS X El Capitan

-Thanks
[Enter steps to reproduce below:]
1. Open core.clj
2. Repl-toggle (ctrl-alt-, shift-L)
3. Error is produced

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package, v1.1.10
### Stack Trace

Uncaught Error: Cannot find module '/Users/Alcatraz/.atom/packages/proto-repl/lib/lein-runner.coffee'

```
At module.js:340

Error: Cannot find module '/Users/Alcatraz/.atom/packages/proto-repl/lib/lein-runner.coffee'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:53:23)
    at new Task (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:35:26)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:17:14)
    at LocalReplProcess.module.exports.LocalReplProcess.start (/Users/Alcatraz/.atom/packages/proto-repl/lib/local-repl-process.coffee:63:27)
    at Repl.module.exports.Repl.startProcessIfNotRunning (/Users/Alcatraz/.atom/packages/proto-repl/lib/repl.coffee:94:3)
    at Object.module.exports.ProtoRepl.toggle (/Users/Alcatraz/.atom/packages/proto-repl/lib/proto-repl.coffee:170:13)
    at Object.module.exports.ProtoRepl.toggleCurrentEditorDir (/Users/Alcatraz/.atom/packages/proto-repl/lib/proto-repl.coffee:188:6)
    at atom-workspace.subscriptions.add.atom.commands.add.proto-repl:toggle-current-project-clj (/Users/Alcatraz/.atom/packages/proto-repl/lib/proto-repl.coffee:19:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -8:21.9.0 proto-repl:pretty-print (atom-text-editor.editor.is-focused)
  2x -6:39.5.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused)
 10x -5:53.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:08.6.0 proto-repl:toggle-current-project-clj (atom-text-editor.editor.is-focused)
     -1:31.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:00.7.0 proto-repl:toggle-current-project-clj (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "proto-repl": {
    "leinPath": "/usr/local/bin/lein",
    "refreshOnReplStart": true
  }
}
```
### Installed Packages

``` coffee
# User
proto-repl, v1.1.10

# Dev
No dev packages
```

**Comment by jasongilman** [comment]
Try restarting Atom. It looks like some code has not loaded correctly.

**Comment by xpndrobserved** [comment]
I installed JDK and restarted Atom. Works like a charm now. Thank you and thanks for the REPL!
