### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getInput' of null

### ISSUE THREAD

**Issue by jinwg** [jasongilman/proto-repl#207]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package, v1.4.10

### Stack Trace

Uncaught TypeError: Cannot read property 'getInput' of null

```
At /Users/jin/.atom/packages/proto-repl/lib/views/ink-console.coffee:105

TypeError: Cannot read property 'getInput' of null
    at InkConsole.module.exports.InkConsole.executeEnteredText (/Users/jin/.atom/packages/proto-repl/lib/views/ink-console.coffee:105:22)
    at /Users/jin/.atom/packages/proto-repl/lib/views/ink-console.coffee:36:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Console._eval (/Users/jin/.atom/packages/ink/lib/console/console.js:235:20)
    at HTMLButtonElement.onclick (/Users/jin/.atom/packages/ink/lib/console/console.js:101:56)
```

### Commands

```
  4x -2:07.0 core:select-left (atom-text-editor.editor.is-focused)
  3x -1:57.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:44.7.0 proto-repl:clear-repl (div.cell)
     -1:42 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:41.8.0 proto-repl:run-all-tests (atom-text-editor.editor)
 16x -1:34.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:22.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  3x -0:57.2.0 proto-repl:refresh-namespaces (div.cell)
     -0:46.3.0 proto-repl:super-refresh-namespaces (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:45.2.0 proto-repl:run-all-tests (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:31.9.0 core:copy (div.output.stream)
  3x -0:19.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:04.6.0 proto-repl:pretty-print (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:03.1.0 proto-repl:pretty-print (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "proto-repl": {
    "autoScroll": false
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.11.2 (active)
ink, v0.6.2 (active)
Parinfer, v1.16.0 (active)
proto-repl, v1.4.10 (active)
proto-repl-charts, v0.4.0 (active)
set-syntax, v0.3.2 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by lyndsysimon** [comment]
Me too.

## Steps to reproduce

1. Start a repl
2. In the repl window, enter `(+ 1 1)`

## Installed packages

```
Built-in Atom Packages (89)
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.45.0
├── base16-tomorrow-dark-theme@1.3.0
├── base16-tomorrow-light-theme@1.3.0
├── one-dark-ui@1.6.2
├── one-light-ui@1.6.2
├── one-dark-syntax@1.5.0
├── one-light-syntax@1.5.0
├── solarized-dark-syntax@1.0.5
├── solarized-light-syntax@1.0.5
├── about@1.7.0
├── archive-view@0.62.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.13.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.4
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── bookmarks@0.42.0
├── bracket-matcher@0.82.2
├── command-palette@0.39.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.202.2
├── fuzzy-finder@1.4.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.0
├── link@0.31.2
├── markdown-preview@0.158.8
├── metrics@1.1.2
├── notifications@0.65.1
├── open-on-github@1.2.1
├── package-generator@1.0.1
├── settings-view@0.243.1
├── snippets@1.0.4
├── spell-check@0.68.4
├── status-bar@1.4.1
├── styleguide@0.47.2
├── symbols-view@0.113.1
├── tabs@0.103.0
├── timecop@0.33.2
├── tree-view@0.210.0
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.35.0
├── wrap-guide@0.38.2
├── language-c@0.54.0
├── language-clojure@0.22.1
├── language-coffee-script@0.48.0
├── language-csharp@0.13.0
├── language-css@0.40.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.43.0
├── language-html@0.47.1
├── language-hyperlink@0.16.1
├── language-java@0.24.0
├── language-javascript@0.122.0
├── language-json@0.18.3
├── language-less@0.29.6
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.8.0
├── language-python@0.45.1
├── language-ruby@0.70.2
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.0
├── language-shellscript@0.23.0
├── language-source@0.9.0
├── language-sql@0.25.0
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.12
└── language-yaml@0.27.1

Community Packages (8) /Users/lyndsysimon/.atom/packages
├── Parinfer@1.16.0
├── activate-power-mode@1.1.0
├── highlight-selected@0.11.2
├── ink@0.6.2
├── lisp-paredit@0.5.4
├── proto-repl@1.4.10
├── set-syntax@0.3.2
└── tool-bar@1.0.1
```

**Comment by xykj61** [comment]
Me too, except I get `Uncaught TypeError: Cannot read property 'constructor' of null`. Just by launching a remote REPL and adding `(+ 1 1)`.

**Comment by jasongilman** [comment]
I'm not seeing this issue. @KeatonDunsford or @lyndsysimon can you produce a stack trace of the problem. Are you both just trying to execute text entered at the REPL?

**Comment by DeathRay1977** [comment]
I am seeing the same when hitting the run button at the top of the REPL tab.

ypeError: Cannot read property 'getInput' of null
    at InkConsole.module.exports.InkConsole.executeEnteredText (/Users/nfa02/.atom/packages/proto-repl/lib/views/ink-console.coffee:105:22)
    at /Users/nfa02/.atom/packages/proto-repl/lib/views/ink-console.coffee:36:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Console._eval (/Users/nfa02/.atom/packages/ink/lib/console/console.js:235:20)
    at HTMLButtonElement.onclick (/Users/nfa02/.atom/packages/ink/lib/console/console.js:101:56)

**Comment by lyndsysimon** [comment]
@jasongilman 

The problem only occurs when I use the "Toggle Current Project Clj" command to start a repl, but not when I connect to an existing nrepl server.

### Stacktrace:

```
TypeError: Cannot read property 'getInput' of null
    at InkConsole.module.exports.InkConsole.executeEnteredText (/Users/lyndsysimon/.atom/packages/proto-repl/lib/views/ink-console.coffee:105:22)
    at /Users/lyndsysimon/.atom/packages/proto-repl/lib/views/ink-console.coffee:36:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Console._eval (/Users/lyndsysimon/.atom/packages/ink/lib/console/console.js:235:20)
    at atom-text-editor.consoleEvaluate (/Users/lyndsysimon/.atom/packages/ink/lib/console/console.js:43:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by matthewdaniel** [comment]
i was able to rectify this by using my lein.bat full path c:\Users\my-user\\.lein\bin\lein.bat. Also I had it entered into the boot path and not the lein path. After i made those changes it is working without having to connect to existing server

**Comment by okc0mputer** [comment]
I only started receiving this error after installing Java 9, which prevented lein from running altogether.  After removing it, everything started working again.

**Comment by didibus** [comment]
I think this happens if you start the default lein project, such as when toggle a repl inside an Atom buffer that has no file.

**Comment by AlJohri** [comment]
Just got this error as well.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package 1.4.20


### Stack Trace

Uncaught TypeError: Cannot read property 'getInput' of null

```
At /Users/johria/.atom/packages/proto-repl/lib/views/ink-console.coffee:108

TypeError: Cannot read property 'getInput' of null
    at InkConsole.module.exports.InkConsole.executeEnteredText (/packages/proto-repl/lib/views/ink-console.coffee:108:22)
    at /packages/proto-repl/lib/views/ink-console.coffee:36:30
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Console._eval (/packages/ink/lib/console/console.js:235:20)
    at HTMLButtonElement.onclick (/packages/ink/lib/console/console.js:101:56)
```

### Commands

```
  2x -8:50.3.0 core:close (input.hidden-input)
     -1:15.5.0 editor:split-selections-into-lines (ul.list-inline.tab-bar.inset-panel)
     -1:13.4.0 proto-repl:clear-repl (ul.list-inline.tab-bar.inset-panel)
     -1:07.6.0 proto-repl:toggle (ul.list-inline.tab-bar.inset-panel)
  4x -1:07.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
highlight-selected 0.13.1 
Hydrogen 1.12.0 
ink 0.6.5 
lisp-paredit 0.5.5 
Parinfer 1.17.0 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.3 
proto-repl 1.4.20 
proto-repl-charts 0.4.1 
Sublime-Style-Column-Selection 1.7.4 
swackets 0.26.0 
tool-bar 1.1.0 
```

**Comment by AlJohri** [comment]
This happens to me when I press the run button:

![screen shot 2017-04-27 at 7 14 50 pm](https://cloud.githubusercontent.com/assets/2790092/25508079/cf0b4512-2b7d-11e7-914a-ab31fa7a575b.png)

**Comment by ron-wolf** [comment]
Another stack trace where the REPL prevents insertion of a newline. Not sure what else would be required to reproduce. Hope this helps!

### Steps to reproduce

1. Open new REPL in project
2. Type line of input (e.g., `(require 'clojure-getting-started.web)`)
3. Press <kbd>return</kbd>


### Environment

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package 1.4.20


### Stack Trace

Uncaught TypeError: Cannot read property 'getInput' of null

```
At /Users/Fallback/.atom/packages/proto-repl/lib/views/ink-console.coffee:108

TypeError: Cannot read property 'getInput' of null
    at InkConsole.module.exports.InkConsole.executeEnteredText (/packages/proto-repl/lib/views/ink-console.coffee:108:22)
    at /packages/proto-repl/lib/views/ink-console.coffee:36:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Console._eval (/packages/ink/lib/console/console.js:235:20)
    at /packages/ink/lib/console/console.js:43:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

(empty)

### Non-Core Packages

```
atom-beautify 0.29.24 
clojure-indent 0.2.0 
file-icons 2.1.5 
improved-chester-atom-syntax 0.3.0 (disabled) 
ink 0.6.5 
proto-repl 1.4.20 
release-notes 0.53.0 
scroll-through-time 0.2.0 (disabled) 
```

**Comment by marcoslhc** [comment]
__Precondition__: This happens with the repl open _with or without_ a document opened

1. Type anything in the repl: `(+ 1 2)`
2. press enter

Also I get:
```
java.io.FileNotFoundException: Could not locate compliment/core__init.class or compliment/core.clj on classpath.
```

after dismissing and trying to continue type

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package 1.4.20

### Profiles.clj
```
{:user {:plugins [[cider/cider-nrepl "0.14.0"]
                  [venantius/ultra "0.5.1"]
                  [com.jakemccrary/lein-test-refresh "0.18.1"]
                  [proto-repl "0.3.1"]]}}
{:debug-repl {:resource-paths [#=(eval (System/getenv "PATH_TO_TOOLS_JAR"))]
              :repl-options {:nrepl-middleware [debug-middleware.core/debug-middleware]}
              :dependencies [[debug-middleware #=(eval (System/getenv "DEBUG_MIDDLEWARE_VERSION"))]]}}
```

### Stack Trace

Uncaught TypeError: Cannot read property 'getInput' of null

```
At /Users/marcoslh/.atom/packages/proto-repl/lib/views/ink-console.coffee:108

TypeError: Cannot read property 'getInput' of null
    at InkConsole.module.exports.InkConsole.executeEnteredText (/packages/proto-repl/lib/views/ink-console.coffee:108:22)
    at /packages/proto-repl/lib/views/ink-console.coffee:36:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Console._eval (/packages/ink/lib/console/console.js:235:20)
    at /packages/ink/lib/console/console.js:43:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -4:15.9.0 proto-repl:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-newton-dark-syntax.theme-one-dark-ui)
     -4:15.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
 12x -3:21.1.0 core:backspace (input.hidden-input)
     -3:02.2.0 console:evaluate (input.hidden-input)
  2x -2:57.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:17.5.0 proto-repl:exit-repl (input.hidden-input)
     -2:13.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:01.3.0 proto-repl:toggle (input.hidden-input)
     -1:38.1.0 console:evaluate (input.hidden-input)
     -1:32.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:08.1.0 console:evaluate (input.hidden-input)
     -1:06.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:05.7.0 console:evaluate (input.hidden-input)
  5x -1:03.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:03.3.0 console:evaluate (input.hidden-input)
     -0:00.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-django 0.3.2 
atom-typescript 11.0.3 
autocomplete-java 1.2.7 
busy-signal 1.4.1 
color-picker 2.2.5 
django-templates 0.5.0 
editorconfig 2.2.2 
emmet 2.4.3 
ex-mode 0.15.0 
file-icons 2.1.7 
git-log 0.4.1 
git-plus 7.9.2 
git-tab-status 1.9.2 
highlight-selected 0.13.1 
ink 0.6.5 
intentions 1.1.2 
language-lisp 0.2.0 
language-matlab 0.2.1 
language-nunjucks 4.1.0 
language-rust 0.4.10 
language-viml 1.1.3 
linter 2.1.4 
linter-coffeelint 1.2.1 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-javac 1.9.4 
linter-jscs 4.1.2 
linter-jshint 3.1.2 
linter-python-pep8 0.2.0 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.0 
lisp-paredit 0.5.5 
merge-conflicts 1.4.5 
monokai 0.24.0 
newton-dark-syntax 1.1.7 
newton-dark-ui 1.1.2 
Parinfer 1.18.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
pretty-json 1.6.3 
proto-repl 1.4.20 
proto-repl-charts 0.4.1 
react 0.16.2 
remote-sync 4.1.5 
set-syntax 0.3.2 
sort-lines 0.14.0 
symbols-tree-view 0.14.0 
tesla-atom 4.0.0 
tool-bar 1.1.0 
vim-mode-plus 0.93.0 
```

**Comment by pedro-w** [comment]
I can't reproduce this on my PC but I note that for most reports where a platform is reported, it seems to be Macintosh.

**Comment by dviius** [comment]
I am working on a Mac, and this problem has recurred.  It happens after certain updates to Proto-REPL/atom.  Is there a way to rollback these updates, when a problem occurs?

The most recent atom-ink (June 15) update caused the REPL to stop, but I didn't note the error/stack messages.
A Proto-REPL update, a few hours later, resolved the problem but left Proto-REPL very slow to respond.
Today (June 16) I updated to atom-ink 0.7.2, and get this error.  Proto-REPL remains unusably slow to respond to my actions.

**Comment by Zerim** [comment]
Running into this issue as well on Mac, while connecting to a remote Nrepl. Is there a known working combination of `proto-repl` and `ink` I can fall back to?

**Comment by dviius** [comment]
Regarding the slow response - I resolved this by disabling all Git update packages.
The problem might be resolved since but, I don't use Git, so...

**Comment by torbjornvatn** [comment]
Still no updates on this? I keep hitting `enter` instead of `shift + enter` and get this error

**Comment by green-coder** [comment]
I have the problem too.

**Comment by Nek** [comment]
I've just bumped into the problem.

**Comment by DVious** [comment]
I just ran into this problem, again, and my previous 'workaround' doesn't work.

I'm pretty sure that, with ANY update to ink, like I ran yesterday, I re-encounter this problem.

**Comment by skershaw** [comment]
Also experiencing this problem after updating ink

**Comment by skershaw** [comment]
Is there any solution for this problem yet?

**Comment by connorbensyl** [comment]
I am also having this problem.
It seems like whenever I start with a "new" repl, as in I reinstalled it, it works the first time I start it. Then every time I try to do (+ 1 1) after that it gives me this error.


1. start repl
2. Enter + 1 1

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package 1.4.24


### Stack Trace

Uncaught TypeError: Cannot read property 'getInput' of null

```
At C:\Users\Connor\.atom\packages\proto-repl\lib\views\ink-console.coffee:108

TypeError: Cannot read property 'getInput' of null
    at InkConsole.module.exports.InkConsole.executeEnteredText (/packages/proto-repl/lib/views/ink-console.coffee:108:23)
    at /packages/proto-repl/lib/views/ink-console.coffee:36:30
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1213350)
    at Console._eval (/packages/ink/lib/console/console.js:234:20)
    at HTMLButtonElement.onclick (/packages/ink/lib/console/console.js:102:56)
```

### Commands

```
     -1:15.1.0 proto-repl:toggle (atom-pane.pane.active)
     -1:12 editor:newline (input.hidden-input)
  2x -1:10.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:51.8.0 proto-repl:toggle (ul.list-inline.tab-bar.inset-panel)
 34x -0:45 core:backspace (input.hidden-input)
     -0:31.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
highlight-selected 0.16.0 
ink 0.10.2 
lisp-paredit 0.6.0 
parinfer 1.23.0 
proto-repl 1.4.24 
script 3.25.0 
set-syntax 0.4.0 
tool-bar 1.2.0 
```

`

**Comment by jose598** [comment]
I had same problem, just try to reload atom but first stop repl connection. it should works.
