### ISSUE TITLE
lein new ... hangs with proto-repl profiles.clj

### ISSUE THREAD

**Issue by thomas-shares** [jasongilman/proto-repl#210]
Hi,

I had the stack trace below after adding the line  [proto-repl "0.3.1"] to my ~/.lein/profiles.clj. Once I removed it the various Leiningen commands worked again.

I tried several lein new commands and got this each time I ran it with the above line included. 

$ lein -version
Leiningen 2.7.1 on Java 1.8.0_112 Java HotSpot(TM) 64-Bit Server VM

This is Mac OS X

Caused by: java.io.FileNotFoundException: Could not locate clojure/data/priority_map__init.class or clojure/data/priority_map.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name., compiling:(clojure/core/cache.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)

**Comment by jasongilman** [comment]
I think you might need to run lein install. Proto REPL lib depends on core async which transitively requires clojure.data.priority-map. 

Excerpt from `lein deps :tree`

```
[org.clojure/core.async "0.2.374"]
   [org.clojure/tools.analyzer.jvm "0.6.9"]
     [org.clojure/core.memoize "0.5.8"]
       [org.clojure/core.cache "0.6.4"]
         [org.clojure/data.priority-map "0.0.4"]
```

**Comment by thomas-shares** [comment]
ok, I'll give it a try and see if that fixes things. Thank you.

**Comment by jasongilman** [comment]
Closing this issue. Please reopen if you think this is a proto-repl issue.
