### ISSUE TITLE
Autoscrolling in the background causes exception

### ISSUE THREAD

**Issue by jasongilman** [jasongilman/proto-repl#29]
If Clojure code is executing and continually outputing data and you move the clojure repl behind another editor (perhaps even make it lose focus) then an exception is printed. `Cannot read property 'setScrollBottom' of null`

**Comment by jasongilman** [comment]
I tried to reproduce this with printing a lot of text to the background but I couldn't seem to get it. If anyone sees this please capture the stack trace and paste here along with proto repl version.

**Comment by jasongilman** [comment]
This is Atom version 1.4.3

```
TypeError: Cannot read property 'setScrollBottom' of null
    at atom-text-editor.TextEditorElement.setScrollBottom (/Users/foo/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:366:28)
    at atom-text-editor.TextEditorElement.scrollToBottom (/Users/foo/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:374:19)
    at TextEditor.module.exports.TextEditor.scrollToBottom (/Users/foo/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2711:46)
    at ReplTextEditor.module.exports.ReplTextEditor.autoscroll (/Users/foo/.atom/packages/proto-repl/lib/repl-text-editor.coffee:173:20)
    at ReplTextEditor.module.exports.ReplTextEditor.appendText (/Users/foo/.atom/packages/proto-repl/lib/repl-text-editor.coffee:191:8)
    at Repl.module.exports.Repl.appendText (/Users/foo/.atom/packages/proto-repl/lib/repl.coffee:154:22)
    at LocalReplProcess.appendText (/Users/foo/.atom/packages/proto-repl/lib/repl.coffee:87:39)
    at /Users/foo/.atom/packages/proto-repl/lib/local-repl-process.coffee:50:8
    at /Users/foo/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/Users/foo/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/foo/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ChildProcess.<anonymous> (/Users/foo/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by jasongilman** [comment]
I haven't seen this in a while. I believe that it was fixed with another pull request.
