### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fromId' of undefined

### ISSUE THREAD

**Issue by matemite** [jasongilman/proto-repl#321]
[Enter steps to reproduce:]

1. Open Atom
2. Try to start a REPL from Packages>proto-repl>Start REPL.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package 1.4.24

### Stack Trace

Uncaught TypeError: Cannot read property 'fromId' of undefined

```
At /Users/user/.atom/packages/proto-repl/lib/views/ink-console.coffee:29

TypeError: Cannot read property 'fromId' of undefined
    at InkConsole.module.exports.InkConsole.startConsole (/packages/proto-repl/lib/views/ink-console.coffee:29:29)
    at /packages/proto-repl/lib/views/ink-console.coffee:24:6)
    at Repl.module.exports.Repl.consumeInk (/packages/proto-repl/lib/repl.coffee:50:19)
    at Object.prepareRepl (/packages/proto-repl/lib/proto-repl.coffee:230:10)
    at Object.toggle (/packages/proto-repl/lib/proto-repl.coffee:223:8)
    at /packages/proto-repl/lib/proto-repl.coffee:123:32)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347598)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718718)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:726641)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -0:05.3.0 proto-repl:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
busy-signal 2.0.1 
ink 0.11.0 
intentions 1.1.5 
linter 2.3.1 
linter-joker 4.1.0 
linter-ui-default 1.8.0 
lisp-paredit 0.6.0 
parinfer 1.23.0 
proto-repl 1.4.24 
rainbow-delimiters 2.1.2 
```

**Comment by matemite** [comment]
Downgrading to 0.10.2 helped with the issue. 
Try: apm install ink@0.10.2

**Comment by javiqm12** [comment]
To downgrade ink to version 0.10.2 is not a solution for me as I am using Atom to develop in Julia and Juno needs ink@0.11.6
A real solution will be highly appreciated, meanwhile I'll move my learning clojure experience to other IDE.

**Comment by sagrebi** [comment]
good is running

**Comment by sagrebi** [comment]
apm install ink@0.10.2 is good solution for me think my friends

**Comment by silvermind86** [comment]
Nowadays i'm only working with clojure, so `apm install ink@0.10.2` do the trick to me.

**Comment by gustavobertolino** [comment]
Downgrading to @0.10.2 works for me, but with this version I lost **autocomplete** in my proto-REPL window, as follows

![Selection_005_highlighted](https://user-images.githubusercontent.com/25723294/89738395-7b59ac00-da4e-11ea-968c-9e78cf6dd855.jpg)

Atom 1.49.0
proto-repl 2.10.0
Ubuntu 18.04

**Comment by allentiak** [comment]
Hi,
Any news regarding this?

**Comment by phunni** [comment]
Also encountering this problem:

```
TypeError: Cannot read property 'fromId' of undefined
    at InkConsole.module.exports.InkConsole.startConsole (/home/paul/.atom/packages/proto-repl/lib/views/ink-console.coffee:29:29)
    at new InkConsole (/home/paul/.atom/packages/proto-repl/lib/views/ink-console.coffee:24:6)
    at Repl.module.exports.Repl.consumeInk (/home/paul/.atom/packages/proto-repl/lib/repl.coffee:50:19)
    at Object.prepareRepl (/home/paul/.atom/packages/proto-repl/lib/proto-repl.coffee:230:10)
    at Object.toggle (/home/paul/.atom/packages/proto-repl/lib/proto-repl.coffee:223:8)
    at HTMLElement.subscriptions.add.atom.commands.add.proto-repl:toggle (/home/paul/.atom/packages/proto-repl/lib/proto-repl.coffee:123:32)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:405:43)
    at CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:292:17)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/lib/atom/src/atom-environment.js:1583:19)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:323:47)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```
