### ISSUE TITLE
Uncaught Port should be > 0 and < 65536. Received NaN.

### ISSUE THREAD

**Issue by gw666** [jasongilman/proto-repl#322]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package 1.4.24

### Stack Trace

Uncaught Port should be > 0 and < 65536. Received NaN.

```
At net.js:1013

RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received NaN.
    at lookupAndConnect (net.js:1013:13)
    at Socket.connect (net.js:987:5)
    at Object.connect (net.js:153:35)
    at Object.connect (/packages/proto-repl/node_modules/jg-nrepl-client/src/nrepl-client.js:194:29)
    at NReplConnection.module.exports.NReplConnection.start (/packages/proto-repl/lib/process/nrepl-connection.coffee:36:19)
    at RemoteReplProcess.module.exports.RemoteReplProcess.start (/packages/proto-repl/lib/process/remote-repl-process.coffee:23:11)
    at Repl.module.exports.Repl.startRemoteReplConnection (/packages/proto-repl/lib/repl.coffee:124:16)
    at NReplConnectionView.confirmCallback (/packages/proto-repl/lib/proto-repl.coffee:263:13)
    at NReplConnectionView.module.exports.NReplConnectionView.onConfirm (/packages/proto-repl/lib/views/nrepl-connection-view.coffee:48:8)
    at /packages/proto-repl/lib/views/nrepl-connection-view.coffee:28:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -9:39.4.0 proto-repl:remote-nrepl-connection (input.hidden-input)
     -9:34.5.0 core:paste (input.hidden-input)
     -9:00.5.0 core:confirm (input.hidden-input)
     -6:47.7.0 command-palette:toggle (div.tool-panel.tree-view)
     -6:35.2.0 proto-repl:remote-nrepl-connection (div.tool-panel.tree-view)
     -6:30.3.0 core:confirm (input.hidden-input)
     -6:10.9.0 command-palette:toggle (input.hidden-input)
     -3:30.4.0 proto-repl:remote-nrepl-connection (input.hidden-input)
     -3:11.2.0 core:paste (input.hidden-input)
  5x -3:09.8.0 core:backspace (input.hidden-input)
     -3:03.0 core:confirm (input.hidden-input)
     -2:48.7.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -1:32 proto-repl:remote-nrepl-connection (input.hidden-input)
     -1:13.2.0 core:confirm (input.hidden-input)
 10x -1:10.1.0 core:backspace (input.hidden-input)
  2x -0:59.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ink 0.11.0 
lisp-paredit 0.6.0 
proto-repl 1.4.24 
```

**Comment by gw666** [comment]
Problem went away when I started a REPL using 'Start project from open project.clj'
