### ISSUE TITLE
Uncaught Error: Cannot find module '/Users/raphael/.atom/packages/proto-repl/lib/repl-process.cof...

### ISSUE THREAD

**Issue by raphaelyancey** [jasongilman/proto-repl#61]
Steps to reproduce the bug:
1. Upgrade to **0.15.1**

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package, v0.15.1
### Stack Trace

Uncaught Error: Cannot find module '/Users/raphael/.atom/packages/proto-repl/lib/repl-process.coffee'

```
At module.js:338

Error: Cannot find module '/Users/raphael/.atom/packages/proto-repl/lib/repl-process.coffee'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:53:23)
    at new Task (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:35:26)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:17:14)
    at Repl.module.exports.Repl.startProcessIfNotRunning (/Users/raphael/.atom/packages/proto-repl/lib/repl.coffee:96:3)
    at Object.module.exports.ProtoRepl.toggle (/Users/raphael/.atom/packages/proto-repl/lib/proto-repl.coffee:190:5)
    at atom-workspace.subscriptions.add.atom.commands.add.proto-repl:toggle (/Users/raphael/.atom/packages/proto-repl/lib/proto-repl.coffee:69:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:37.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 proto-repl:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {},
  "proto-repl": {
    "leinPath": "/usr/local/bin/lein"
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.7.0
proto-repl, v0.15.1

# Dev
No dev packages
```

**Comment by jasongilman** [comment]
Did you try restarting Atom? This looks like a problem with reloading the code after proto repl was installed. I usually have to restart Atom after upgrading Proto REPL.

**Comment by jasongilman** [comment]
I believe this was an issue shown directly after loading proto repl. If you can reproduce the problem please reopen the issue.
