### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir 'atom://config'

### ISSUE THREAD

**Issue by jmgimeno** [jasongilman/proto-repl#68]
[Enter steps to reproduce below:]
1. Try to open a REPL

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package, v0.15.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir 'atom://config'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir 'atom://config'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at LocalReplProcess.module.exports.LocalReplProcess.getRootProject (/Users/jmgimeno/.atom/packages/proto-repl/lib/local-repl-process.coffee:35:20)
    at LocalReplProcess.module.exports.LocalReplProcess.start (/Users/jmgimeno/.atom/packages/proto-repl/lib/local-repl-process.coffee:54:20)
    at Repl.module.exports.Repl.startProcessIfNotRunning (/Users/jmgimeno/.atom/packages/proto-repl/lib/repl.coffee:89:16)
    at Object.module.exports.ProtoRepl.toggle (/Users/jmgimeno/.atom/packages/proto-repl/lib/proto-repl.coffee:178:13)
    at atom-workspace.subscriptions.add.atom.commands.add.proto-repl:toggle (/Users/jmgimeno/.atom/packages/proto-repl/lib/proto-repl.coffee:86:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -3:25.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -3:19 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -3:09.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:05.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -2:49.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:24 application:add-project-folder (span.name.icon.icon-file-directory)
     -1:39.8.0 proto-repl:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:26.9.0 core:paste (atom-text-editor#proto-repl.leinPath.editor.mini.is-focused)
     -0:16.8.0 core:save (input#proto-repl.refreshBeforeRunningSingleTest.)
     -0:01.9.0 proto-repl:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "proto-repl": {
    "leinPath": "/usr/local/bin/lein"
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.14.0
language-idris, v0.4.2
language-scala, v1.1.6
minimap, v4.19.0
proto-repl, v0.15.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by phillc73** [comment]
I have the same issue. I'm using Debian Sid 64-bit.

I've upgraded to the latest version and unfortunately, the issue is also still present in v0.16.0

Stack trace: 

```
Error: ENOENT: no such file or directory, scandir 'atom://config'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at LocalReplProcess.module.exports.LocalReplProcess.getRootProject (/home/phillc/.atom/packages/proto-repl/lib/local-repl-process.coffee:35:20)
    at LocalReplProcess.module.exports.LocalReplProcess.start (/home/phillc/.atom/packages/proto-repl/lib/local-repl-process.coffee:54:20)
    at Repl.module.exports.Repl.startProcessIfNotRunning (/home/phillc/.atom/packages/proto-repl/lib/repl.coffee:88:9)
    at Object.module.exports.ProtoRepl.toggle (/home/phillc/.atom/packages/proto-repl/lib/proto-repl.coffee:178:14)
    at atom-workspace.subscriptions.add.atom.commands.add.proto-repl:toggle (/home/phillc/.atom/packages/proto-repl/lib/proto-repl.coffee:82:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by jasongilman** [comment]
What did you do that triggered the issue? Did you just toggle the REPL? What did you have open at the time?

It looks like a problem scanning for a project file.

**Comment by jmgimeno** [comment]
I think the problem was that I has two different projects in the tree view. When there's only one open project it works fine.

**Comment by phillc73** [comment]
These are my first steps with Clojure, so I've been following the book [Clojure for the Brave and True](http://www.braveclojure.com). Instead of using Emacs as they suggest, I decided to use Atom instead.

I have a fresh installation of Atom 1.5.3, with a custom theme. I have proto-repl, proto-repl-charts and parinfer installed.

Steps:
1. File Menu > Add Project Folder
2. Navigate to src folder/project name, select .clj file
3. Packages Menu > proto-repel > start REPL

Then the error is thrown.

Screen shot attached. 

I wouldn't be surprised if it was user error somewhere..... 
![proto-repl-error](https://cloud.githubusercontent.com/assets/815126/13380204/c9d1fa8e-de3d-11e5-8312-d7daf6e22e02.png)

**Comment by phillc73** [comment]
I've fixed this. Once I closed the "config" folder/project, as seen in the screen shot above, based on feedback from @jmgimeno, everything now works fine. 

Looks like the issues is certainly with having two projects open at once.

**Comment by jasongilman** [comment]
I just figured out and fixed the problem as well. It was only happening when the top folder open was the atom config folder. When it's open atom reports the root directory as "atom://.atom/config" This doesn't work with the standard node functions for paths. I skip trying to find the project.clj of a folder that looks like that.

**Comment by jasongilman** [comment]
Note that selecting "Start REPL" will look for a project.clj file at the root of the project. If you want to open a selected one like in the event you have multiple project folders, open the project.clj, then select "Start REPL from open project.clj" from the menu.
