### ISSUE TITLE
[1.1.0] Failed to load the proto-repl package

### ISSUE THREAD

**Issue by ronjouch** [jasongilman/proto-repl#79]
Steps to reproduce:
1. Update Proto-REPL to 1.1.0 from Atom

→ After the upgrade and at each startup, I see the error message below. Had no problem before upgrading. Uninstalling/reinstalling the package didn't help.

**Atom Version**: 1.5.4
**System**: Arch Linux
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package, v1.1.0
### Stack Trace

Failed to load the proto-repl package

```
At Cannot find module './proto_repl/goog/bootstrap/nodejs.js'

Error: Cannot find module './proto_repl/goog/bootstrap/nodejs.js'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/ronj/.atom/packages/proto-repl/lib/proto-repl.coffee:4:1)
    at Object.<anonymous> (/home/ronj/.atom/packages/proto-repl/lib/proto-repl.coffee:4:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at /usr/share/atom/resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:30)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  2x -0:31.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "about",
      "archive-view",
      "background-tips",
      "language-csharp",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "metrics",
      "spell-check",
      "welcome",
      "package-generator",
      "symbols-view",
      "release-notes",
      "autocomplete-snippets",
      "dev-live-reload",
      "deprecation-cop",
      "image-view",
      "open-on-github",
      "timecop",
      "update-package-dependencies",
      "tasks",
      "build",
      "react",
      "language-coffee-script",
      "language-java",
      "language-less",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-todo",
      "bookmarks",
      "language-go",
      "styleguide",
      "autocomplete-atom-api"
    ]
  },
  "proto-repl": {
    "displayHelpText": false
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.14.0
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.0
editorconfig, v1.2.4
file-icons, v1.6.18
highlight-line, v0.11.1
highlight-selected, v0.11.2
linter, v1.11.3
linter-clojure, v1.1.2
linter-flake8, v1.13.0
linter-shellcheck, v1.1.0
proto-repl, v1.1.0
tab-numbers, v0.3.0

# Dev
No dev packages
```

**Comment by jasongilman** [comment]
Thanks for reporting this quickly. I have made a fix and pushed 1.1.1. Testing it now.

**Comment by jasongilman** [comment]
It seems like it fixed the problem.

**Comment by ronjouch** [comment]
@jasongilman thanks for the quick patch! I confirm the problem is fixed :+1: .

---

However, now I get this when starting the REPL. This is a ClojureScript/Reagent/Figwheel project, I'm very much a Clojure newbie and I _think_ I already saw that but am not sure. So that may or may not be related to 1.1.1; maybe I just borked something in my project. Any idea?

```
Starting REPL with lein in /home/ronj/lt
nREPL server started on port 35601 on host 127.0.0.1 - nrepl://127.0.0.1:35601
Refreshing code...
Refresh failed: FileNotFoundException Could not locate user__init.class or user.clj on classpath.  clojure.lang.RT.load (RT.java:456)
--------------------
```

**Comment by jasongilman** [comment]
I think you've stumbled across a problem with the Clojure script support. You can totally ignore that error. It won't cause any issues. But if you want to hide it for now disable the refresh at startup option in the settings. 

If you see any more Clojure script issues please throw a comment in here: https://github.com/jasongilman/proto-repl/issues/54

**Comment by ronjouch** [comment]
> I think you've stumbled across a problem with the Clojure script support. You can totally ignore that error. It won't cause any issues. But if you want to hide it for now disable the refresh at startup option in the settings.

Correct, thanks :) . Suggestion: maybe add a caption to this preference, saying it should currently be disabled for Cljs projects?

Will chime in #54 if I stumble on other cljs quirks. Thanks again for your work!
