### ISSUE TITLE
Atom must be restarted when upgrading Proto REPL

### ISSUE THREAD

**Issue by dnando** [jasongilman/proto-repl#85]
[Enter steps to reproduce below:]
1. I simply started the repl using the Start REPL command from the Packages menu in the GUI.

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package, v1.1.3
### Stack Trace

Uncaught Error: Cannot find module '/Users/nando/.atom/packages/proto-repl/lib/lein-runner.coffee'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:279

Error: Cannot find module '/Users/nando/.atom/packages/proto-repl/lib/lein-runner.coffee'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:53:23)
    at new Task (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:35:26)
    at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:17:14)
    at LocalReplProcess.module.exports.LocalReplProcess.start (/Users/nando/.atom/packages/proto-repl/lib/local-repl-process.coffee:63:27)
    at Repl.module.exports.Repl.startProcessIfNotRunning (/Users/nando/.atom/packages/proto-repl/lib/repl.coffee:87:16)
    at Object.module.exports.ProtoRepl.toggle (/Users/nando/.atom/packages/proto-repl/lib/proto-repl.coffee:177:17)
    at atom-workspace.subscriptions.add.atom.commands.add.proto-repl:toggle (/Users/nando/.atom/packages/proto-repl/lib/proto-repl.coffee:19:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:01.6.0 proto-repl:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "subway-seoul"
    ],
    "disabledPackages": [
      "language-hyperlink"
    ]
  },
  "proto-repl": {}
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.14.0
jsformat, v0.9.0
language-cfml, v0.12.0
language-lucee, v0.2.0
linter, v1.11.3
linter-clojure, v1.1.2
proto-repl, v1.1.3
subway-seoul, v1.0.9
tool-bar, v0.2.1

# Dev
No dev packages
```

**Comment by dnando** [comment]
I uninstalled and reinstalled proto-repl, and now it seems to be working again.

**Comment by jasongilman** [comment]
I've seen this happen when proto repl is upgraded and you don't restart atom. I don't see this issue with other packages so I wonder if I'm doing something wrong with the way dependencies are loaded. Note that lein-runner.coffee was moved to a subfolder during a recent update. It was still looking for lein runner in the old location.

**Comment by jasongilman** [comment]
I asked about this problem here https://discuss.atom.io/t/package-code-not-reloading-during-an-update/32411
